# Site settings
title: Jaehyeon's blog
email: dottami@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Journey on full stack data product development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jaehyeon-kim.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  jaehyeon-kim
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
