# Site settings
title: Jaehyeon's Blog
email: dottami@gmail.com
description: "Blog about full stack data product development"
baseurl: ""
url: "http://jaehyeon-kim.github.io"
twitter_username: 
github_username:  jaehyeon-kim

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap