# Site settings
title: lauris.github.io
email: lauris@discuss.lv
description: "Personal blog about programming, hacking, open-source, startups, git, vim, linux, etc."
baseurl: ""
url: "https://lauris.github.io"
twitter_username: lauriswat
github_username:  lauris

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap