services:
  hugo:
      image: peaceiris/hugo:v0.123.0-full
      command: server -D -F -E --poll 700ms --bind=0.0.0.0
      container_name: hugo
      volumes:
        - $PWD:/src
        - /etc/ssl/certs:/etc/ssl/certs
      ports:
        - "1313:1313"
