---
layout: post
title: "2014-12-01-Data-Manipulation-Summary"
description: ""
category: R
tags: [knitr,reshape2,plyr,dplyr]
---
{% include JB/setup %}

This is a summary of data manipulation with `reshape2`, `plyr` and `dplyr`. It has the same order to _Chapter 15 Getting Your Data into Shape_ of [R Graphics Cookbook](http://shop.oreilly.com/product/0636920023135.do) but a different data sets are used.

```{r loadPackages, message=FALSE, warning=FALSE}
library(knitr)
library(reshape2)
library(plyr)
library(dplyr)
```

#### 1 creating, adding, deleting, renaming and reordering data frames/columns
##### 1) creating a data frame
```{r creatingDataFrame}
df <- data.frame(g = c("A","B","C"), x = 1:3)

lst <- list(g = c("A","B","C"), x = 1:3)
df <- as.data.frame(lst)
```

##### 2) adding a column
```{r addingColumn}
df$nc <- 12:14
kable(df[1,], format = "markdown")
```

##### 3) deleting a column
```{r deletingColumn}
df$nc <- NULL
```

##### 4) renaming columns
```{r renamingColumn}
names(df) <- c("group", "value")

# rename by name
names(df)[names(df) == "group"] <- c("g")
# rename by index
names(df)[2] <- "x"
names(df)
```













